# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\edit_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditHistory(object):
    def setupUi(self, EditHistory):
        EditHistory.setObjectName("EditHistory")
        EditHistory.resize(400, 192)
        self.gridLayout = QtWidgets.QGridLayout(EditHistory)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listView = QtWidgets.QListView(EditHistory)
        self.listView.setObjectName("listView")
        self.verticalLayout_2.addWidget(self.listView)
        self.lineEdit = QtWidgets.QLineEdit(EditHistory)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnAdd = QtWidgets.QPushButton(EditHistory)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout.addWidget(self.btnAdd)
        self.bntUpdate = QtWidgets.QPushButton(EditHistory)
        self.bntUpdate.setObjectName("bntUpdate")
        self.verticalLayout.addWidget(self.bntUpdate)
        self.btnDelete = QtWidgets.QPushButton(EditHistory)
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout.addWidget(self.btnDelete)
        self.btnSave = QtWidgets.QPushButton(EditHistory)
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout.addWidget(self.btnSave)
        self.btnExit = QtWidgets.QPushButton(EditHistory)
        self.btnExit.setObjectName("btnExit")
        self.verticalLayout.addWidget(self.btnExit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(EditHistory)
        QtCore.QMetaObject.connectSlotsByName(EditHistory)

    def retranslateUi(self, EditHistory):
        _translate = QtCore.QCoreApplication.translate
        EditHistory.setWindowTitle(_translate("EditHistory", "Command History"))
        self.btnAdd.setText(_translate("EditHistory", "Add"))
        self.bntUpdate.setText(_translate("EditHistory", "Update"))
        self.btnDelete.setText(_translate("EditHistory", "Delete"))
        self.btnSave.setText(_translate("EditHistory", "Save and Exit"))
        self.btnExit.setText(_translate("EditHistory", "Exit"))
